SAMPLE_QUESTIONS = [
    "Qual o horário de funcionamento da Seção Técnica de Gestão de Pessoas?",
    "Como solicitar declaração de vínculo com a UNESP?",
    "Qual o contato da Diretoria Técnica de Informática?",
    "Onde fica a Seção Técnica de Contabilidade?",
    "Como agendar consulta na Seção Técnica de Saúde?",
    "Quais documentos são necessários para matrícula na graduação?",
    "Como funciona o processo de remoção de servidores?",
    "Qual o prazo para entrega de relatórios de estágio probatório?",
    "Como solicitar diárias e passagens?",
    "Quais os canais de comunicação da Seção Técnica de Comunicações?",
    "Como solicitar manutenção de equipamentos?",
    "Qual o procedimento para emissão de diploma?",
    "Como funciona o Centro de Educação Infantil do ICT?",
    "Quais os serviços oferecidos pela Seção Técnica de Materiais?",
    "Como solicitar acesso à rede Wi-Fi do ICT?",
    "Qual o calendário acadêmico do ICT-SJC?",
    "Como solicitar certidão de tempo de serviço?",
    "Quais as normas de segurança do laboratório?",
    "Como participar de programa de pós-graduação?",
    "Qual o procedimento para solicitar afastamento para capacitação?",
]
